name: Production Deployment Flow
concurrency: production-deploy

on: 
  push: 
    branches:
      - main

jobs:
  buildAndDeploy:
      runs-on: ubuntu-latest 

      steps:
        - uses: actions/checkout@v2
        
        - name: Install CDK Dependencies
          run: npm install

        - name: Build API Code
          run: cd src && npm install && npm run build

        - name: Where Am I
          run: ls

        - name: Creating / Updating Infrastructure
          uses: youyo/aws-cdk-github-actions@v2
          with:
            cdk_subcommand: 'deploy'
            cdk_stack: ${{ secrets.API_STACK_NAME }}
            cdk_args: '--require-approval never'
            actions_comment: false
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
